name: OD_benchmark
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn=1.0.2
  - matplotlib
  - seaborn
  - scipy
  - cvxopt
  - pytorch
  - pip
  - pip:
    - cython
    - tensorflow
    - pyod
    - eif
    - combo
    - tqdm
    - rrcf
